# Generated by Django 2.1.7 on 2019-03-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainActor', models.CharField(max_length=250)),
                ('filmTitle', models.CharField(max_length=500)),
                ('director', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=1000)),
            ],
        ),
    ]
